apiVersion: v1
kind: Service
metadata:
  name: password-reset-service
spec:
  selector:
    app: password-reset
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

